[package]
name = "semif-engine-tch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
semif-types = { workspace = true }
semif-core = { workspace = true }
semif-engine = { workspace = true }
thiserror = { workspace = true }
libloading = "0.8"
sha2 = { workspace = true }
tch = "=0.23.0"
