[package]
name = "semif-engine-llamacpp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
semif-types = { workspace = true }
semif-core = { workspace = true }
semif-engine = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
libloading = "0.8"
